"""The offline generators write where the app reads.

Two files are generated by a script and committed to the tree — the car
inventory and the track catalog — and each is read at runtime through a
Settings default. Nothing links the two ends, so moving one (as #57 moved both
into the package) silently leaves the generator writing to a path nobody
reads: `backend/data/` still exists, so there is not even an error to notice.

These tests are that link. They import the scripts by path because `scripts/`
is a directory of entry points, not an importable package.
"""

import importlib.util
from pathlib import Path
from types import ModuleType

from app.config import Settings

SCRIPTS = Path(__file__).resolve().parents[1] / "scripts"


def _load(name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / f"{name}.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_car_generator_writes_where_the_app_reads() -> None:
    assert _load("build_car_metadata").OUT == Settings().cars_json


def test_the_track_generator_writes_where_the_app_reads() -> None:
    assert _load("build_track_metadata").OUT == Settings().tracks_json


def test_both_generated_files_are_present_and_shipped() -> None:
    """They are committed, and they live under the package so a wheel carries
    them (`[tool.setuptools.package-data]` takes `app/data/*.json`)."""
    settings = Settings()
    package = settings.cars_json.parent
    for path in (settings.cars_json, settings.tracks_json, settings.track_signatures_json):
        assert path.is_file(), f"{path} is missing"
        assert path.parent == package, f"{path} is outside the shipped data directory"
