// Generates the two files the converter reads as this app's "package":
//
//   .design-sync/ds-entry.tsx  the bundle entry (esbuild -> window.GT7)
//   index.d.ts                 the type-discovery barrel, pointing at the
//                              declarations tsc emits into ds-types/
//
// Both are derived from src/, so a new component needs no edit here. Run via
// .design-sync/build-inputs.sh (cfg.buildCmd).

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// main.tsx mounts the real app (and would run on bundle load); App.tsx only
// default-exports, which `export *` does not carry.
const SKIP = new Set(["src/main.tsx", "src/App.tsx"]);
// Type and fixture modules that aren't .tsx: the demo telemetry frame and lap
// set the overlay's placeholder mode already uses, plus the widget metadata.
// Previews and designs both need them to render a widget without a console.
const EXTRA = [
  "src/lib/demoFrame.ts",
  "src/lib/widgetMeta.ts",
  "src/lib/overlay.ts",
  "src/lib/types.ts",
  // The series palette and the lap-time/number formatters: any timing UI built
  // on this library needs them to look like the app.
  "src/lib/colors.ts",
  "src/lib/format.ts",
  // The channel catalogue and playback speeds: the option sets the analysis
  // toolbars are built from, so a design doesn't have to retype them.
  "src/lib/channels.ts",
  "src/lib/playback.ts",
  // The layout model and its presets. Without these the grid components are
  // exported but unusable: nothing can build the LayoutConfig they take.
  "src/lib/layout.ts",
  "src/lib/dashPresets.ts",
  // The race-line map's layer model and brake markers, and the stint helpers
  // the analysis view gates its stint panel on.
  "src/lib/mapLayers.ts",
  "src/lib/stint.ts",
  // The fuel/stint projection and the alert thresholds the strategy and alert
  // widgets are driven by — a dashboard built on this library needs both.
  "src/lib/strategy.ts",
  "src/lib/alerts.ts",
  // The stores the components read. Exporting them is what lets a design (and
  // a preview card) put the UI into a real state — a connected status bar, a
  // toast on screen — instead of its empty one.
  "src/store/settings.ts",
  "src/store/telemetry.ts",
  "src/store/toasts.ts",
  "src/store/analysis.ts",
  "src/store/engineer.ts",
];

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const modules = [
  ...walk("src")
    .filter((p) => p.endsWith(".tsx") && !/\.(test|spec|stories)\./.test(p))
    .filter((p) => !SKIP.has(p.split("\\").join("/"))),
  ...EXTRA,
]
  .map((p) => p.split("\\").join("/").replace(/\.tsx?$/, ""))
  .sort();

const header = (what) => `// Generated by .design-sync/gen-entry.mjs — ${what}.\n// Do not edit; re-run .design-sync/build-inputs.sh.\n\n`;

writeFileSync(
  ".design-sync/ds-entry.tsx",
  header("bundle entry for the claude.ai/design sync") +
    modules.map((m) => `export * from "@/${m.replace(/^src\//, "")}";`).join("\n") +
    "\n",
);

writeFileSync(
  "index.d.ts",
  header("type-discovery barrel over the tsc-emitted declarations") +
    modules.map((m) => `export * from "./ds-types/${m}";`).join("\n") +
    "\n",
);

console.error(`gen-entry: ${modules.length} modules`);
