"""Car ID -> car lookup.

The inventory ships with the package (`app/data/cars.json`), generated by
`scripts/build_car_metadata.py` from Polyphony's own car list, so a fresh
install with no network resolves every car it knows about on the first packet.
`car_source.py` refreshes it in the background; both write this file, and this
module is the only thing that reads it.

Before #57 the bundled file was `data/cars.csv`, two columns of id and name.
`load()` still reads that shape when it is handed a .csv, so an install that
has one — pinned by GT7_CARS_CSV, or written by an older release — keeps
working with names alone; it just answers nothing to the richer questions.
"""

from __future__ import annotations

import csv
import json
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

# Bumped when the shape of cars.json changes in a way a reader must know about.
# Stored alongside the data and in the settings table, so a release that
# changes the schema re-seeds rather than trusting rows built by the old one.
SCHEMA_VERSION = 1


@dataclass(frozen=True, slots=True)
class Car:
    """What GT7's own car list publishes about one car.

    Numeric fields are 0 where the source does not publish a value — an EV has
    no displacement, a kart no measured torque — rather than None, so callers
    can format them without a null check. `year` is 0 for the cars whose names
    carry no year at all ("Red Bull X2014 Standard", "FT-1").
    """

    id: int
    name: str
    full_name: str = ""
    manufacturer: str = ""
    year: int = 0
    category: str = ""      # "Gr.N" (road), "Gr.1".."Gr.4", "Gr.B", "Gr.X"
    drivetrain: str = ""    # "FR", "FF", "MR", "RR", "4WD"
    aspiration: str = ""    # "NA", "TC", "SC", "TC+SC", "EV"
    displacement_cc: int = 0
    power_bhp: int = 0
    torque_kgfm: float = 0.0
    weight_kg: int = 0
    length_mm: int = 0
    width_mm: int = 0
    height_mm: int = 0
    performance_points: float = 0.0

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class Inventory:
    """A parsed cars.json: the cars plus the provenance of the file."""

    cars: dict[int, Car] = field(default_factory=dict)
    generated: str = ""
    source: str = ""
    schema_version: int = SCHEMA_VERSION


def dumps(inventory: Inventory) -> str:
    """Serialise to the on-disk shape. The scraper and the runtime refresh both
    write through here, so there is one definition of the format."""
    return json.dumps(
        {
            "meta": {
                "generated": inventory.generated,
                "source": inventory.source,
                "schema_version": inventory.schema_version,
                "cars": len(inventory.cars),
            },
            "cars": {
                str(cid): {k: v for k, v in car.as_dict().items() if k != "id"}
                for cid, car in sorted(inventory.cars.items())
            },
        },
        indent=1,
        ensure_ascii=False,
        sort_keys=False,
    )


def loads(raw: str) -> Inventory:
    """Parse the on-disk shape. Rows that cannot be read are skipped, not fatal:
    one malformed entry must not cost the other 573 their names."""
    data = json.loads(raw)
    meta = data.get("meta") or {}
    inv = Inventory(
        generated=str(meta.get("generated", "")),
        source=str(meta.get("source", "")),
        schema_version=int(meta.get("schema_version", 0)),
    )
    fields = {f for f in Car.__dataclass_fields__ if f != "id"}
    for key, value in (data.get("cars") or {}).items():
        try:
            car_id = int(key)
            inv.cars[car_id] = Car(id=car_id, **{k: v for k, v in value.items() if k in fields})
        except (AttributeError, TypeError, ValueError):
            # A key that is not a number, or an entry that is not an object.
            continue
    return inv


class CarDatabase:
    def __init__(self) -> None:
        self._cars: dict[int, Car] = {}
        self.generated: str = ""
        self.schema_version: int = 0

    def load(self, path: Path) -> None:
        """Populate from cars.json, or from a legacy two-column cars.csv.

        Never raises: a missing or unreadable inventory leaves every car
        showing as `Car #{id}`, which is worse than it was, not broken.
        """
        if not path.exists():
            log.warning("car inventory not found at %s; car names will show as IDs", path)
            return
        try:
            raw = path.read_text(encoding="utf-8")
        except OSError:
            log.exception("car inventory at %s could not be read", path)
            return

        if path.suffix.lower() == ".csv":
            self._load_csv(raw, path)
            return
        try:
            inv = loads(raw)
        except (ValueError, AttributeError):
            log.exception("car inventory at %s is not valid; car names will show as IDs", path)
            return
        self._cars = inv.cars
        self.generated = inv.generated
        self.schema_version = inv.schema_version
        log.info("loaded %d cars (inventory generated %s)", len(self._cars), inv.generated or "?")

    def _load_csv(self, raw: str, path: Path) -> None:
        cars: dict[int, Car] = {}
        for row in csv.DictReader(raw.splitlines()):
            try:
                car_id = int(row["id"])
                cars[car_id] = Car(id=car_id, name=row["name"])
            except (KeyError, TypeError, ValueError):
                continue
        self._cars = cars
        self.generated = ""
        self.schema_version = 0
        log.info(
            "loaded %d car names from the legacy CSV at %s; regenerate cars.json "
            "for manufacturer, year, drivetrain and the rest",
            len(cars), path,
        )

    def replace(self, inventory: Inventory) -> None:
        """Swap in a freshly fetched inventory (the background refresh)."""
        self._cars = inventory.cars
        self.generated = inventory.generated
        self.schema_version = inventory.schema_version

    def inventory(self) -> Inventory:
        """What is loaded, as an Inventory — the base a refresh merges onto."""
        return Inventory(
            cars=dict(self._cars),
            generated=self.generated,
            source="",
            schema_version=self.schema_version,
        )

    @property
    def count(self) -> int:
        return len(self._cars)

    def name(self, car_id: int) -> str:
        car = self._cars.get(car_id)
        return car.name if car else f"Car #{car_id}"

    def all(self) -> dict[int, Car]:
        """Every car, for the callers that fill a whole table at once."""
        return dict(self._cars)

    def get(self, car_id: int) -> Car | None:
        """The full record, or None for an id the inventory does not carry.

        Callers that only need something to print want `name()`; this is for
        the ones that have somewhere to put a manufacturer.
        """
        return self._cars.get(car_id)
